# Generated by Django 4.2.7 on 2025-07-22 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_username', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('follower_count', models.IntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('content_categories', models.CharField(choices=[('lifestyle', 'Lifestyle'), ('food', 'Food & Dining'), ('beauty', 'Beauty & Fashion'), ('fitness', 'Fitness & Health'), ('tech', 'Technology'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='lifestyle', max_length=50)),
                ('weekly_allowance', models.IntegerField(default=1000)),
                ('current_allowance', models.IntegerField(default=1000)),
                ('allowance_reset_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_category', models.CharField(choices=[('restaurant', 'Restaurant'), ('spa', 'Spa & Wellness'), ('fitness', 'Fitness & Gym'), ('retail', 'Retail & Shopping'), ('beauty', 'Beauty & Salon'), ('entertainment', 'Entertainment'), ('tech', 'Technology'), ('other', 'Other')], default='restaurant', max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
